#!/usr/bin/env node
/**
 * Regenerates the Phase 16 per-composition audit from the designs themselves.
 *
 *   node scripts/stitch-audit.mjs
 *
 * The audit is a *derived* document: every number in it comes from
 * `stitch-fidelity.mjs --all --verbose --coverage`, which is why this generator
 * is committed rather than kept beside the document. Porting a screen changes the
 * numbers, and a document that no longer matches the tree is how the phase ended
 * up claiming 45 verbatim ports it did not have — so regenerate it whenever a row's
 * status changes.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const FRONTEND = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const PROJECT = path.resolve(FRONTEND, "..");
const OUT = path.join(
  PROJECT,
  ".planning/phases/TCS-JL-16-replace-the-current-screens-with-the-frontend-stitch-designs/16-AUDIT.md",
);

// The sweep exits 1 while any composition diverges; stdout carries the report.
let output = "";
try {
  output = execFileSync(
    process.execPath,
    ["scripts/stitch-fidelity.mjs", "--all", "--verbose", "--coverage"],
    { cwd: FRONTEND, encoding: "utf8", env: process.env, maxBuffer: 64 * 1024 * 1024 },
  ).toString();
} catch (error) {
  output = `${error.stdout ?? ""}${error.stderr ?? ""}`;
}

const strict = new Map();
const coverage = new Map();
const failed = new Set();
const raw = output.split(/\r?\n/);
let index = 0;

while (index < raw.length) {
  const line = raw[index];
  const verbose = line.match(
    /^(\S+)\s+\[region <(\w+)>\]\s+(\d+) classes · (\d+) glyphs · (\d+) headings · (\d+) awaiting · (\d+) declared drops · (\d+) source tokens$/,
  );
  if (verbose !== null) {
    strict.set(verbose[1], {
      region: verbose[2],
      classes: Number(verbose[3]),
      glyphs: Number(verbose[4]),
      headings: Number(verbose[5]),
      awaiting: Number(verbose[6]),
      drops: Number(verbose[7]),
      tokens: Number(verbose[8]),
    });
  }
  const cover = line.match(/^COVERAGE (\S+) absent=(\d+)\/(\d+)\/(\d+)$/);
  if (cover !== null) {
    const entry = { classes: [], glyphs: [], headings: [] };
    for (const kind of ["classes", "glyphs", "headings"]) {
      const next = raw[index + 1] ?? "";
      if (!next.startsWith(`  ${kind}: `)) continue;
      const body = next.slice(kind.length + 4);
      entry[kind] =
        kind === "headings"
          ? body.split(" | ").map((value) => value.trim()).filter(Boolean)
          : body.split(/\s+/).filter(Boolean);
      index += 1;
    }
    coverage.set(cover[1], entry);
  }
  if (line.startsWith("FIDELITY-FAIL")) {
    // The tail is a bare folder name per failing composition, then indented problems.
    for (const tail of raw.slice(index + 1)) if (/^\S+$/.test(tail)) failed.add(tail);
  }
  index += 1;
}

const rows = [...strict.keys()].sort().map((folder) => {
  const count = strict.get(folder);
  const miss = coverage.get(folder) ?? { classes: [], glyphs: [], headings: [] };
  const divergent = miss.classes.length + miss.glyphs.length + miss.headings.length;
  return {
    folder,
    count,
    miss,
    divergent,
    strictPass: !failed.has(folder),
    verdict:
      divergent === 0 ? "**carried**" : divergent > 40 ? "divergent (large)" : "divergent (small)",
  };
});
rows.sort((a, b) => a.divergent - b.divergent);

const totals = {
  classes: rows.reduce((sum, row) => sum + row.miss.classes.length, 0),
  glyphs: rows.reduce((sum, row) => sum + row.miss.glyphs.length, 0),
  headings: rows.reduce((sum, row) => sum + row.miss.headings.length, 0),
};
const carried = rows.filter((row) => row.divergent === 0);
const passing = rows.filter((row) => row.strictPass);

const doc = [
  "# Phase 16 — Per-Composition Fidelity Audit",
  "",
  "Generated by `node frontend/scripts/stitch-audit.mjs`, which runs",
  "`node frontend/scripts/stitch-fidelity.mjs --all --verbose --coverage`. Regenerate it whenever a row's",
  "status changes: the numbers below are derived from the tree, and a stale audit is how this phase came to",
  "claim ports it did not have.",
  "",
  "## What was measured",
  "",
  "- **Region:** the composition's `<main>` (or the whole `<body>` when it has no `<main>`).",
  "- **Composition tokens:** the distinct class names, `data-icon`/`material-symbols-outlined` glyphs and",
  "  heading texts that appear inside that region.",
  "- **Absent from the frontend (coverage):** how many of those tokens appear **nowhere in any file under",
  "  `frontend/src`** — comments and test files excluded. This is the strict measure, and the honest answer to",
  "  *did the design make it into the product at all*. It is deliberately generous to the app: a token carried",
  "  in a different file than the ledger names does not count as absent.",
  "- **Strict pass:** whether the composition satisfies `stitch-fidelity.mjs` against its own row — every class,",
  "  glyph and heading carried by the row's declared sources, or declared dropped in the row's `Not carried`",
  "  column.",
  "- **Verdict `carried`:** none of the composition's tokens is absent from `frontend/src` anywhere — the coverage",
  "  measure, not the strict one. It is blind to declared drops, so a row can be `carried` while declaring gaps, and",
  "  it is blind to which file carried a token, so a row can be `carried` while its own sources do not. `divergent",
  "  (small | large)` counts the tokens that are absent everywhere.",
  "",
  "## Result",
  "",
  `- **${rows.length}** compositions audited.`,
  `- **${passing.length}** pass the strict per-row check: ${passing.map((row) => `\`${row.folder}\``).join(", ")}.`,
  "  A pass is not the same as carried: passing means every token is either present or declared dropped.",
  `- **${carried.length}** have no token absent from the frontend at all: ${carried.map((row) => `\`${row.folder}\``).join(", ")}.`,
  `- **${rows.length - passing.length}** fail the strict check.`,
  `- Absent from the entire frontend, across all ${rows.length}: **${totals.classes} class tokens**, **${totals.glyphs} glyph names**, **${totals.headings} heading texts** (${totals.classes + totals.glyphs + totals.headings} tokens).`,
  "",
  "## Per composition",
  "",
  "| Composition | Region | Composition tokens (cls/gly/hdg) | Absent from frontend (cls/gly/hdg) | Awaiting | Strict | Verdict |",
  "|---|---|---|---|---|---|---|",
  ...rows.map(
    (row) =>
      `| \`${row.folder}\` | \`<${row.count.region}>\` | ${row.count.classes}/${row.count.glyphs}/${row.count.headings} ` +
      `| ${row.miss.classes.length}/${row.miss.glyphs.length}/${row.miss.headings.length} | ${row.count.awaiting} ` +
      `| ${row.strictPass ? "pass" : "**fail**"} | ${row.verdict} |`,
  ),
  "",
  "## What this means",
  "",
  "The compositions are the design; this phase's stated goal is that each screen's markup **is** its",
  "composition. Measured against the whole frontend, that holds for the compositions listed as carried above and",
  "does not hold for the rest. On the other screens the app renders the composition's *layout and hierarchy* with",
  "its own class spelling (`brand-*` / `slate-*` tokens, shared `CARD` constants, `lucide-react` icons in place of",
  "`material-symbols-outlined` ligatures) and drops the mockups' sample content.",
  "",
  "Where a screen shares one component with several compositions that each specify their own treatment — the six",
  "auth screens share one `AuthCard` and one `Input`, and each mockup draws its own card width, padding, brand",
  "badge and field border — closing the gap means giving the shared component a per-composition variant, not",
  "renaming classes on the page.",
  "",
  "## Ledger defects found",
  "",
  "- **Divergence recorded nowhere.** Most rows declare no `Not carried` tokens and no `Awaiting slots` while",
  "  their screens do not carry the composition.",
  "- **A fabrication entry that was real product copy.** `tcs_joining_tracker_error_and_empty_route_states`",
  "  declared `The page you are looking for does not exist` as a fabrication, but",
  "  `frontend/src/components/ErrorPanels.tsx` renders exactly that string (test-pinned). The check reported it",
  "  as a fabrication leak; the entry was wrong and now names the mockup's own copy instead.",
  "- **A row pointing at a file that does not exist.** `tcs_joining_tracker_error_and_empty_route_states`",
  "  declared `src/pages/NotFoundPage.tsx`; that page lives in `src/pages/index.tsx`.",
  "- **Under-declared sources.** Rows name one or two files while the screen renders from shared components",
  "  (`authCard.tsx`, `Input.tsx`, `PostCard.tsx`, `ErrorPanels.tsx`, …). This inflates the declared-source gap",
  "  without changing what the app shows, which is why this audit leads with the frontend-wide measure.",
  "",
  "## Tooling defects found and fixed",
  "",
  "- `stitch-fidelity.mjs --all` aborted on the **first** structural fault, so one stale row hid the state of",
  "  every composition after it. Structural faults are now collected per composition and the sweep finishes.",
  "- The glyph check only looked inside string literals, so a ligature rendered as a React JSX text child",
  "  (`<span …>arrow_back</span>`) was reported missing even when the source carried it. Glyphs are now matched",
  "  against the whole source minus its comments.",
  "- The heading check compared case-sensitively, so a mockup's hard-coded `YOUR RECRUITMENT PROGRESSION` was",
  "  reported missing where the app renders title case under Tailwind's `uppercase`. Headings are now compared",
  "  case-insensitively.",
  "- Nothing measured how much of a design was in the product at all. `--coverage` adds that measure, and",
  "  `--all` prints it for every composition.",
  "",
  "## How to reproduce",
  "",
  "```bash",
  "node frontend/scripts/stitch-audit.mjs                                        # rewrite this document",
  "cd frontend && node scripts/stitch-fidelity.mjs --all --verbose --coverage    # the sweep behind it",
  "cd frontend && node scripts/stitch-fidelity.mjs --screen <composition>        # one composition",
  "```",
  "",
  "The sweep exits 1 while any composition diverges. That is the state of the phase, not a broken build:",
  "`npm run test:run`, `npm run typecheck` and `npm run build` are the gates that cover the shipped app.",
  "",
  "## Tokens absent from the whole frontend",
  "",
  "Every token below was searched for across all of `frontend/src` and found nowhere.",
  "",
  ...rows.flatMap((row) => {
    const { miss } = row;
    if (miss.classes.length + miss.glyphs.length + miss.headings.length === 0) return [];
    return [
      `### \`${row.folder}\``,
      "",
      ...(miss.classes.length > 0 ? [`- **classes:** \`${miss.classes.join("` `")}\``] : []),
      ...(miss.glyphs.length > 0 ? [`- **glyphs:** \`${miss.glyphs.join("` `")}\``] : []),
      ...(miss.headings.length > 0 ? [`- **headings:** ${miss.headings.join(" · ")}`] : []),
      "",
    ];
  }),
];

writeFileSync(OUT, `${doc.join("\n")}\n`, "utf8");
console.log(`wrote ${path.relative(PROJECT, OUT)}`);
console.log(
  `${rows.length} compositions · strict-pass ${passing.length} · carried ${carried.length} · ` +
    `absent ${totals.classes}/${totals.glyphs}/${totals.headings}`,
);
